apiVersion: v1
kind: ConfigMap
metadata:
  name: <populate>-configmap
  namespace: <populate>
data:
  SMB_USER_NAME: <populate>
  SMB_USER_DOMAIN: <populate>
  SMB_SERVICE_NAME: <populate>
  SMB_DIRECTORY: <populate>
  ARCHIVE_FILE_DIRECTORY: <populate>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <populate>-secret
  namespace: <populate>
stringData:
  SMB_USER_PASSWORD: <populate>
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: <populate>-archive-backup
  namespace: <populate>
spec:
  timeZone: 'America/Chicago'
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: <populate>
            image: emerconnelly/k8s-cronjob-smb-export:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: <populate>
              mountPath: <populate>
            envFrom:
            - configMapRef:
                name: <populate>-configmap
            - secretRef:
                name: <populate>-secret
          restartPolicy: OnFailure
          volumes:
          - name: <populate>
            persistentVolumeClaim:
              claimName: <populate>
